import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";

import background from "../public/images/backtest.png";
import Content from "../components/Content";
import styles from "../styles/modules/Content.module.css";
import stylesHome from "../styles/modules/Home.module.css";

const backgroundVariants = {
  hidden: {
    opacity: 0,
    scale: 0.98,
    transition: {
      // delay: 2,
      duration: 1,
    },
  },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      delay: 2,
      duration: 2,
    },
  },
};
const item = {
  hidden: {
    opacity: 0,
    x: 0,
    y: 300,
  },
  visible: {
    opacity: 1,
    x: 0,
    y: 0,
    transition: {
      // type: "linear",
      delay: 2,
      ease: "easeOut",
      duration: 0.5,
    },
  },
  exit: {
    opacity: 0,
    x: 0,
    y: 300,
    transition: {
      duration: 0.5,
    },
  },
  transition: {},
};

const container = {
  visible: {
    transition: {
      staggerChildren: 0.5,
    },
  },
  exit: {
    transition: {
      staggerChildren: 0.2,
    },
  },
};

export default function Home({ canonical }) {
  return (
    <>
      <Content>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <motion.div
          initial="hidden"
          animate="visible"
          exit="exit"
          variants={container}
          className={stylesHome.Container}
        >
          <motion.div
            initial="hidden"
            animate="visible"
            exit="hidden"
            variants={backgroundVariants}
            className={stylesHome.BackgroundImage}
          >
            <Image src={background} alt="fds" />
          </motion.div>

          <h1
            className={`${styles.Title} ${styles.TitleNoMargin} ${stylesHome.TextAnimate}`}
          >
            <motion.span variants={item} className={stylesHome.TextAnimateWrap}>
              I'm
            </motion.span>
          </h1>
          <h1
            className={`${styles.Title} ${styles.TitleNoMargin} ${stylesHome.TextAnimate}`}
          >
            <motion.span
              variants={item}
              className={`${styles.Yellow} ${stylesHome.TextAnimateWrap}  ${stylesHome.TextHover}`}
            >
              <Link href="/about" scroll={false}>
                <a>
                  <span className={stylesHome.TextHoverShown}>Maximilian</span>
                  <span className={stylesHome.TextHoverHidden}>About</span>
                </a>
              </Link>
            </motion.span>
          </h1>
          <h1
            className={`${styles.Title} ${styles.TitleNoMargin} ${stylesHome.TextAnimate}`}
          >
            <motion.span
              variants={item}
              className={`${styles.Yellow} ${stylesHome.TextAnimateWrap}  ${stylesHome.TextHover}`}
            >
              <Link href="/work" scroll={false}>
                <a>
                  <span className={stylesHome.TextHoverShown}>Hagerf</span>
                  <span className={stylesHome.TextHoverHidden}>Work</span>
                </a>
              </Link>
            </motion.span>
          </h1>
        </motion.div>
      </Content>
    </>
  );
}
