import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";

import background from "../public/images/backtest.png";
import Content from "../components/Content";
import styles from "../styles/modules/Content.module.css";

const backgroundVariants = {
  hidden: {
    opacity: 0,
    scale: 0.98,
    transition: {
      duration: 1,
    },
  },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      delay: 2,
      duration: 2,
    },
  },
};
const item = {
  hidden: {
    opacity: 0,
    top: 300,
  },
  visible: {
    opacity: 1,
    top: 0,
    transition: {
      ease: "easeOut",
      duration: 0.5,
    },
  },
  exit: {
    opacity: 0,
    top: 300,
    transition: {
      duration: 0.5,
    },
  },
  transition: {},
};

const container = {
  visible: {
    transition: {
      staggerChildren: 0.5,
      delayChildren: 2,
    },
  },
  exit: {
    transition: {
      staggerChildren: 0.2,
    },
  },
};

export default function Home({ canonical }) {
  const [isCoverActive, setIsCoverActive] = useState(false);
  const coverMode = isCoverActive ? styles.HomePhoneCoverActive : "";
  const forceHover = isCoverActive ? styles.HomeTextHoverForce : "";
  const onClick = () => {
    setIsCoverActive(!isCoverActive);
  };

  return (
    <>
      <Head>
        <title>Maximilian Hagerf</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Content>
        <motion.div
          initial="hidden"
          animate="visible"
          exit="exit"
          variants={container}
          className={styles.HomeContainer}
        >
          <motion.div
            initial="hidden"
            animate="visible"
            exit="hidden"
            variants={backgroundVariants}
            className={styles.HomeBackgroundImage}
          >
            <Image src={background} alt="fds" />
          </motion.div>

          <h1
            className={`${styles.Title} ${styles.TitleNoMargin} ${styles.HomeTextAnimate}`}
          >
            <motion.span variants={item} className={styles.HomeTextAnimateWrap}>
              I'm
            </motion.span>
          </h1>
          <h1
            className={`${styles.Title} ${styles.TitleNoMargin} ${styles.HomeTextAnimate}`}
          >
            <motion.span
              variants={item}
              className={`${styles.Yellow} ${styles.HomeTextAnimateWrap}  ${styles.HomeTextHover} ${forceHover}`}
            >
              <Link href="/about" scroll={false}>
                <a>
                  <span className={styles.HomeTextHoverShown}>Maximilian</span>
                  <span className={styles.HomeTextHoverHidden}>About</span>
                </a>
              </Link>
            </motion.span>
          </h1>
          <h1
            className={`${styles.Title} ${styles.TitleNoMargin} ${styles.HomeTextAnimate} ${forceHover}`}
          >
            <motion.span
              variants={item}
              className={`${styles.Yellow} ${styles.HomeTextAnimateWrap}  ${styles.HomeTextHover}`}
            >
              <Link href="/work" scroll={false}>
                <a>
                  <span className={styles.HomeTextHoverShown}>Hagerf</span>
                  <span className={styles.HomeTextHoverHidden}>Work</span>
                </a>
              </Link>
            </motion.span>
          </h1>
        </motion.div>

        <div
          className={`${styles.HomePhoneCover} ${coverMode}`}
          onClick={onClick}
        >
          <span className={styles.HomePhoneCoverText}>Tap anywhere</span>
        </div>
      </Content>
    </>
  );
}
