import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";

// import AnimatedCharacters from "../components/AnimatedCharacters";
import background from "../public/images/backtest.png";
import Content from "../components/Content";
import styles from "../styles/modules/Content.module.css";
import stylesHome from "../styles/modules/Home.module.css";

const backgroundVariants = {
  hidden: {
    opacity: 0,
    scale: 0.98,
    transition: {
      // delay: 2,
      duration: 1,
    },
  },
  visible: {
    opacity: 1,
    scale: 1,
    transition: {
      delay: 2,
      duration: 2,
    },
  },
};
const item = {
  hidden: {
    opacity: 0,
    x: 0,
    y: 300,
  },
  visible: {
    opacity: 1,
    x: 0,
    y: 0,
    transition: {
      // type: "linear",
      ease: "easeOut",
      duration: 0.5,
    },
  },
  exit: {
    opacity: 0,
    x: 0,
    y: 300,
    transition: {
      duration: 0.5,
    },
  },
  transition: {},
};

const container = {
  visible: {
    transition: {
      staggerChildren: 0.5,
    },
  },
  exit: {
    transition: {
      staggerChildren: 0.2,
    },
  },
};

export default function Home({ canonical }) {
  const [isShown, setIsShown] = useState(false);

  function onClick() {}

  return (
    <>
      <Content>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <motion.div
          initial="hidden"
          animate="visible"
          exit="exit"
          variants={container}
          className={stylesHome.Container}
        >
          <motion.div
            initial="hidden"
            animate="visible"
            exit="hidden"
            variants={backgroundVariants}
            className={stylesHome.BackgroundImage}
          >
            <Image src={background} alt="fds" />
          </motion.div>
          <h1
            className={`${styles.Title} ${styles.TitleNoMargin} ${stylesHome.TextAnimate}`}
          >
            <motion.span variants={item} className={stylesHome.TextAnimateWrap}>
              Hi
            </motion.span>
          </h1>
          <h1
            className={`${styles.Title} ${styles.TitleNoMargin} ${stylesHome.TextAnimate}`}
          >
            <motion.span variants={item} className={stylesHome.TextAnimateWrap}>
              I am
            </motion.span>
          </h1>
          <h1
            onMouseEnter={() => setIsShown(true)}
            onMouseLeave={() => setIsShown(false)}
            onClick={onClick}
            className={`${styles.Title} ${styles.TitleNoMargin} ${stylesHome.TextAnimate} ${stylesHome.TextHover}`}
          >
            <motion.span
              variants={item}
              className={`${styles.Yellow} ${stylesHome.TextAnimateWrap}`}
            >
              <Link href="/about" scroll={false}>
                <a>{!isShown ? "Max" : "About"}</a>
              </Link>
            </motion.span>
          </h1>
        </motion.div>
      </Content>
    </>
  );
}
